---
deployment:
      tasks:
        - export DEPLOYPATH=/home/anthrmzw/public_html/portfolio 
        - /bin/cp index.html $DEPLOYPATH                 
        - /bin/cp /<sub_folder>/<file_name> $DEPLOYPATH   
        - /bin cp * $DEPLOYPATH                           
        - /bin cp /<sub_folder>/* $DEPLOYPATH             
        - /bin/cp -r * $DEPLOYPATH                        


